import Gallery from "../components/Gallery";
import NavHeader from "../components/NavHeader";
import { Box } from "@chakra-ui/react";
import Head from "next/head";
import {loadImages} from '../lib/loadImages'

export const getStaticProps = async () => {
  const images = loadImages

  return {
    props: {
      images
    },
  };
};

export default function Home({images}) { 

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Box 
          minH='100vh'
          w='full'
          bgImage={`url(/bgImg.webp)`}
          bgPos='top'
          bgSize='cover'
          color='white'>
          <NavHeader />
          <Gallery images={images} />
        </Box>
      </main>
    </>
  );
}
